### ISSUE TITLE
Desired: add-edges-with-attrs, add-directed-edges-with-attrs, add-undirected-edges-with-attrs

### ISSUE THREAD

**Issue by sergeny** [Engelberg/ubergraph#10]
Currently if I want to add multiple multi-edges between a given pair of vertices and associate different attributes with each edge, there is no good way of doing it. I have to first create the edges, then find them later and associate attributes. Furthermore, if I only want to associate the attributes with e.g. undirected edges that are not mirror edges, but want to have a mixture of various kinds of edges, then I have to be even more careful when picking the edges I want to associate information with.

It would make a lot of sense to have `add-edges-with-attrs`, `add-directed-edges-with-attrs`, `add-undirected-edges-with-attrs`, so I can actually control the process. Alternatively, there can be a way to find the most recent edge.

**Comment by sergeny** [comment]
Workaround: add one edge at a time and use `find-edge` on a pair of nodes to find the new edge, then use `add-attrs`. Should be considerably slower with lots of parallel edges.

**Comment by Engelberg** [comment]
add-edges and add-directed-edges and add-undirected-edges can take edge descriptors with attribute maps.  I see now that the docstring doesn't reflect that, but it is mentioned in the readme.  I'll update the docstring.  See example below.  So there is no need for the extra add-edges-with-attrs, et al., because the existing functions handle both edge descriptors with or without attributes.  Do you agree this is sufficient?

```
=> (pprint (add-edges (multigraph) [:a :b {:color :red}] [:a :b {:color :blue}]))
Multigraph
2 Nodes:
     :a 
     :b 
2 Edges:
     :a <-> :b {:color :red}
     :a <-> :b {:color :blue}
```

**Comment by Engelberg** [comment]
Ah, the reason the docstring for add-edges doesn't talk about the attribute form is that the docstring comes from loom (since this is an implementation of loom's protocol) and this implementation just happens to support this additional feature.  Not sure if there is any way to tweak the loom docstring from ubergraph.  Will need to think about that.  I have just implemented fixes for your other bug reports (thanks!) and will push a new release when I hear back from you on this to make sure the current behavior is what you are looking for.

**Comment by Engelberg** [comment]
I went ahead and released the other changes, but to reiterate, on this particular issue, I think the function can already do what you want.

**Comment by sergeny** [comment]
Yes, looks like it can already do that. So it is probably sufficient to just find a way to make it obvious in the documentation.

**Comment by sergeny** [comment]
E.g. in the documentation for `build-graph`, it says "or build your graph with the more
precise add-nodes, add-nodes-with-attrs, and add-edges functions.", suggesting that there is no `add-edges-with-attrs`.

**Comment by Engelberg** [comment]
I did figure out a way to hack the doc string of loom's add-edges protocol
function, so that is clearer.  I'll look around and see if there are other
places, like build-graph, where this can be clearer.

On Sun, Dec 13, 2015 at 7:02 PM, Sergey Orshanskiy <notifications@github.com
