### ISSUE TITLE
Undirected graphs are not equal if their undirected edges "have different direction"

### ISSUE THREAD

**Issue by sergeny** [Engelberg/ubergraph#12]
That is, if one undirected graph says A->B is the real one and B->A is the mirror one, while another graph says the opposite, they would not be considered equal. Tested in 0.1.7 and 0.1.8.

```
=> (def G1 (ubergraph/add-edges (ubergraph/add-nodes (ubergraph/graph) "first" "second") ["first" "second"]))
=> (def G2 (ubergraph/add-edges (ubergraph/add-nodes (ubergraph/graph) "second" "first") ["second" "first"]))
=> (= G1 G2)
false
```

Note, however, that graph equality can be a surprisingly complicated issue. Say, we have 100 parallel edges between A and B. Then in order to check for equality, we'd have to find out if there's a permutation of the edges so that the corresponding pairs are equal, which may potentially require quadratic time to compare each edge's attribute to each edge's attribute. It would probably require a lot of very subtle unit tests to ensure a consistent semantics, as there are just too many possibilities. Imagine a slew of edges between A and B, some going one way, some the other, some undirectional, some having no attribute, some having {nil []} as the attribute map, some having {nil '()} as the attribute map, some having {nil nil} as the attribute map, some having {} as the attribute map... 

E.g. start from

```
(ug/add-attrs (ug/multigraph [[] {} '()]) [] {})
```

and it will get complicated very quickly.

**Comment by Engelberg** [comment]
Graph _isomorphism_ is a complicated (NP-hard, I believe) problem because you have to consider the possibility that the nodes are permuted.  But the kind of equality I'm testing for is the idea that the graphs are actually the same nodes, with the same edges, and the same attributes attached to each node/edge.  The only thing that makes it complicated is that the edges are stored internally with UUIDs and if the same graph was created in two different ways, the structure would be the same but the UUIDs are different.  This is solved in a reasonable manner by subbing the UUIDs with attribute maps and making sure the frequency of edges between a given pair with certain attributes are the same, e.g., if there are two edges between A and B with attribute {:color :red} in one graph, then there should be two edges between A and B with attribute {:color :red} in the other..  Should be approx O(n + e \* m \* log m) I think, where n is number of nodes, e is number of edges, and m is the maximum number of parallel edges.  And the equality test, of course, passes instantly if they are actually identical, and will usually fail quickly if they are not equal.

You made a good point about how an attribute map of {} should be treated as equivalent to no attribute map at all, and I addressed that.  But beyond that, the equality and hashing semantics of nil, [], '(), and {} should be consistent with Clojure's semantics, and I believe it currently does that, with no further special casing needed.

I'm okay with the fact that A<->B is not considered the same as B<->A.  Mirror edges control one's ability to iterate through the graph's edges and ignore the mirror edges to make sure you are only seeing one direction of the edge for certain algorithms where you need to be sure to visit each edge only once.  But if the mirror edge is pointing the opposite way, you'd get a different direction of the undirected edge in a ignore-mirror-edge iteration through the graph, and I think that's a meaningful distinction.

Again, the key is to think about what this equality predicate is meant to accomplish.  We're not trying to detect general isomorphism.  But without some sort of custom equality predicate, basic test cases like `(is (= (uber/graph [:a :b] [:a :c] [:b :d]) (uber/graph [:a :b] [:a :c] [:b :d])))` would fail (because although the structures are the same, the UUIDs are wrong).  So really, that's the only thing I'm trying to address here, is to make it possible to get sufficiently sane equality semantics so you can write test cases that work as you'd expect.

**Comment by Engelberg** [comment]
Edited the above to read O(n + e \* m \* log m).

**Comment by sergeny** [comment]
Fair point. Though, I still find it very counterintuitive that the direction of undirected edges affects equality. I am not sure it is reasonable to assume that most, or even many, users of Ubergraph would embrace the concept of mirror edges. 

One possible solution would be to always make the "forward" undirected edge from u to v, where u < v (assuming the node labels are comparable), while making the "mirror edge" go from v to u. 

It is also possible to just write a special section in the documentation explaining the current semantics of graph equality (probably a good idea anyway). 
On that note, I'd also explain in the documentation that the attributes for the undirected edge and its "mirror version" get merged together, since it is not entirely obvious. 

Overall, I still find two pieces confusing (though, of course, I greatly appreciate all the work that you've put into it):
- the concept of mirror undirected edges seems an implementation detail that should be hidden in every possible way as semantically irrelevant for the applications that are not interested in it, and
- the possibility of creating undirected graphs with directed edges and vice versa (why then not just have graphs and multigraphs, without distinguishing between e.g. graphs and digraphs?)

**Comment by Engelberg** [comment]
On Sun, Dec 13, 2015 at 6:36 PM, Sergey Orshanskiy <notifications@github.com

> wrote:
> 
> Overall, I still find two pieces confusing (though, of course, I greatly
> appreciate all the work that you've put into it):
> - the concept of mirror undirected edges seems an implementation
>   detail that should be hidden in every possible way as semantically
>   irrelevant for the applications that are not interested in it, and
> 
> It's always useful to get the perspective of active users like yourself.
> Let me see if I can clarify this a bit for you, and you can help me figure
> out what sorts of clarifications would help in the docs.

Loom (and many other graph libraries) simply implement an undirected edge
as two directed edges.  This causes a few problems:
1. If you want to have a directed edge and an undirected edge in the same
   graph, and the undirected graph is just implemented as two directed edges,
   how can you determine whether a given directed edge is actually a directed
   edge, or part of a pair?
2. If you iterate through the graph's edges, how do you make sure you see
   each edge only once?  (Often, as you point out, this can be solved by only
   counting edges where (< (src edge) (dest edge)), with special handling for
   loop edges, but Clojure does not have a "universal comparator" and if we
   want to support arbitrary nodes, this breaks down).
3. How do you keep the attributes in sync for two sides of a pair of
   directed edges which represent a single undirected edge?  (Often this is
   solved with pointers and mutation).

Loom doesn't attempt to solve these problems, but these were key things I
wanted to address with ubergraph.

My solution to the above problems:
1. Two record types and predicates to distinguish directed-edge? and
   undirected-edge?
2. Undirected edges still come in pairs, just like Loom and most other
   graph libraries, but since we can't rely on any kind of natural order, the
   order you give for the two nodes when you initially add the undirected edge
   to the graph is considered the natural or "forward" direction, and the
   other direction becomes the "mirror" edge.  The mirror-edge? predicate lets
   you ignore mirror edges during the edge traversal, if you wish (Loom's
   solution is to just not make any promises, and to say, "If you traverse
   edges, you may see them twice", but that's not really a solution -- it
   means you can't reliably traverse edges for algorithms which require that
   you see each edge exactly once).
3. Keep the attributes in sync by using UUIDs as the "pointer" that both
   sides of the edge use to point at the same set of attributes.

When you realize that the two sides of a undirected edge still denote the
same edge and must share exactly the same attributes, then it is clear that
when you add attributes to either "side" you are merging into the set of
attributes for the overall undirected edge.

Unfortunately, the UUIDs mean that two graphs, constructed in exactly the
same way, don't compare as equal using Clojure's built in structural
equality.  I haven't been able to think of any sort of non-random,
deterministic way to do this that doesn't use pointers and mutation.

I think for the most part, you can safely ignore mirror edges if you don't
need this feature, and you're no worse off than you would be using, say,
Loom.  You've pointed out one thing (the only thing?) that is obviously
different:
(graph [1 2]) is not equal to (graph [2 1])

So then the question is, _should_ these be semantically equal?  I can see
your argument for why they should compare as equal (they both contain an
undirected edge between 1 and 2), and I can also see the argument for why
they shouldn't (in the context of ubergraph, when you create an undirected
edge you have explicit control over which is considered the "forward" edge
and which is the "mirror" edge, and those graphs represent two different
choices).

I'm inclined towards the position that they shouldn't be semantically
equal, because it gives you more control.  If you have a domain where you
have a natural ordering to the nodes, you can write a little helper
function to ensure that edges are always added using that natural order as
the forward direction.

The other reason I lean in that direction is that it simplifies the
implementation.  In general, we can't assume a natural ordering for the
nodes exists, so that rules out certain implementations that would make
these equal.  I'm sure I could tweak the graph equality to make these
compare as equal, but it would potentially have performance implications.
I'd need to do some testing to get a sense for how much it would impact
performance.  Do you have some good, real-world graphs you're using that
you'd like me to run some timing tests on?

Do you have a concrete example where you're creating undirected edges, and
you don't have control over the order in which they are added, and you need
to be sure the graphs compare as equal regardless of which way they are
added, or is this more of a philosophical debate?

You also expressed confusion about:
- the possibility of creating undirected graphs with directed edges and
  vice versa (why then not just have graphs and multigraphs, without
  distinguishing between e.g. graphs and digraphs?)

You are right that both graphs and digraphs permit a mixture of directed
and undirected edges.  The main difference between graphs and digraphs is
the default behavior when you just use the standard add-edges function.
Graphs assume it is undirected, and digraphs assume it is directed.  The
beauty of this is that with one underlying representation, I can satisfy
Loom's protocols for directed graphs as well as Loom's protocols for
undirected graphs, meaning that most of Loom's algorithms work out of the
box on ubergraphs.  Compatibility with Loom's graph ecosystem was a major
goal of ubergraph.

**Comment by sergeny** [comment]
Also, can I add two directed edges, A->B and B->A, to a digraph? Or would I need a multidigraph? Can I have a directed edge from A to B and another undirected edge from A to B in a graph, or would I need a multigraph?

**Comment by Engelberg** [comment]
Digraph is fine for that scenario.

**Comment by Engelberg** [comment]
Actually I'm not certain about your second question.  I'll check the source
and/or test it later. I think for directed and undirected to coexist you
need a multigraph or multidigraph.

**Comment by Engelberg** [comment]
So to reiterate what I said above: in your first example, the directed edges A->B and B->A would not be in conflict; they are distinct edges and can coexist in a digraph (or graph), no multidigraph needed.

I've just double-checked the source to make sure  I'm giving you the right answer on your second example. If you are in an Ubergraph where :allow-parallel? is set to true, of course, there is no problem and adding edges (directed or undirected) just creates fresh edges.

If :allow-parallel? is set to false (i.e., graph or digraph), then here's what happens:
If you try to create a directed edge where there is already an undirected edge, the new edge is not created, but we merge in any attributes to the existing edge.
If you try to create an undirected edge where there is already a directed edge (in either or both directions), the directed edge (or pair of directed edges) is "upgraded" to a single undirected edge and the attributes are all merged together (with attributes from the edge you are trying to add taking precedence).

That's the behavior that seemed the most intuitive to me.  Another option I considered was to throw an error when you try to add a parallel edge to a graph where parallel edges are forbidden, but I wanted to try to do something more useful than that.

So what I said before is correct: if you want a directed and undirected edge between a given pair of nodes to coexist, you need to use an ubergraph that allows parallel edges.

**Comment by Engelberg** [comment]
After thinking about this more and discussing with others, I have come to the conclusion that you are right that (graph [1 2]) should evaluate as equal to (graph [2 1]).  I will be making this change soon.

**Comment by Engelberg** [comment]
I finally had a chance to address the equality issue you raised, and will be deploying as 0.2.0.
So from 0.2.0 onwards, the exact nature of mirror or non-mirrorness of directed edges makes no difference with respect to equality.  so (graph [1 2]) and (graph [2 1]) now evaluate as equal.  Thanks for making me think through this issue.
