### ISSUE TITLE
Create a public API for (:undirected? g) and (:allow-parallel? g).

### ISSUE THREAD

**Issue by sergeny** [Engelberg/ubergraph#14]
Naturally, those functions could be called `undirected? g` and `allow-parallel? g`.

**Comment by Engelberg** [comment]
Good idea.  I won't have a chance to add this before next weekend, but it
seems like a good plan.

On Sun, Dec 13, 2015 at 6:59 PM, Sergey Orshanskiy <notifications@github.com

**Comment by sergeny** [comment]
On the flip side, it would be great to have a public constructor that could create a graph/digraph/multigraph/multidigraph from two booleans; I do not think that `build-graph` allows that. Right now I have essentially a switch statement choosing one out of four constructors.

**Comment by Engelberg** [comment]
You are absolutely right that it would be trivial to implement that, since
that's essentially how the underlying representation of ubergraphs works.
If you would find it useful, I can add that.

On Sun, Dec 13, 2015 at 9:23 PM, Sergey Orshanskiy <notifications@github.com

**Comment by Engelberg** [comment]
Done, will be deploying shortly as version 0.2.0.
I opted for slightly more verbose function names:
`undirected-graph?` and `allow-parallel-edges?`
because I didn't want people to think the plain `undirected?` name might be polymorphic and also test specific edges, rather than only applying to graphs.
