### ISSUE TITLE
all-paths between two nodes

### ISSUE THREAD

**Issue by nlessa** [Engelberg/ubergraph#21]
Hi,
Is there a simple way to get all paths (in an uber digraph) between two nodes?

Sorry in advance if it is a stupid question. :-)

Bests,

Nilton

**Comment by Engelberg** [comment]
This is not an especially common thing to want, because there can be an exponential number of paths between two nodes in any non-trivial graph (even if you ignore cycles).  So it's not built into either ubergraph or loom.

But if you want to find all paths that don't duplicate a vertex (i.e., no cycles within the path), it's a very easy function to write using the ubergraph API.  Basically, it's just a depth-first search, branching to all vertices not contained in the path so far.

You can find Java code here:
http://stackoverflow.com/a/22464491/2392831

It's even easier in Clojure because you don't have to keep copying the path at each branch point - Clojure's immutable data structures amke this a piece of cake.

If you're still stuck, let me know.

**Comment by Engelberg** [comment]
Closing issue.  Since I haven't heard from you, I assume you were able to work out how to do it in ubergraph from the Java code.  If you've coded it and think it would be generally useful and want to contribute it to ubergraph's algorithms, let me know.
