### ISSUE TITLE
graphviz parameters

### ISSUE THREAD

**Issue by masztal** [Engelberg/ubergraph#22]
Hi,
How can I add attributes to graph for graphviz drawing?
For nodes and edges it's trivial, but for graph I can't figure it out.
Thanks,
MM

**Comment by Engelberg** [comment]
I didn't create an API for adding data to a graph itself because I was thinking that like all Clojure data, you could just add additional key-value pairs to the overall graph using Clojure's built-in facilities for manipulating records and maps: assoc, get, etc.

But as a consequence, I really didn't think through how this would map to graphviz.  It shouldn't be too hard to address, but I haven't thought about this yet.  What are graph attributes used for in graphviz?

**Comment by masztal** [comment]
Thanks for reply,
I mean attributes like bgcolor, splines, etc.
What I want to achieve is to draw graph with specified nodes coordinates and curved connections.

**Comment by Engelberg** [comment]
Used your pull request.  Thanks.
