### ISSUE TITLE
little help request on k-core decomposition

### ISSUE THREAD

**Issue by jaromil** [Engelberg/ubergraph#28]
Hi there! is there anyone with some experience working with ubergraph  who can help me understand how feasible it is to implement a k-core decomposition algorithm using it?

here some info on the function: https://arxiv.org/abs/cs/0504107

here an example implementation (very minimal) https://github.com/priyagovindan/NimbleCore

**Comment by Engelberg** [comment]
It looks like it should be straightforward to port the python code you linked to.  Probably the Clojure implementation will be a little simpler, even.  After removing all self-loops and singletons, identify all the nodes with degree less than or equal to 1.  Give those a core number of 1, then remove them from the graph.  Now identify all the nodes with degree less than or equal to 2.  Give those a core number of 2, then remove them from the graph.  And so on.

Do you have experience with Clojure and working with immutable data structures?

**Comment by jaromil** [comment]
Hi, thanks for the encouragement, I guess that's all I needed. I have decent experience with clojure yes, just very little experience with graph algorithms and, while I ordered two books on the subject, will look into experimenting with your library then. Thanks for all your work!

**Comment by Engelberg** [comment]
I'm not sure my above description is exactly correct, because I only briefly scanned the article you linked to.  On second look, it looks like maybe it's this:
After removing all self-loops and singletons, identify all the nodes with degree less than or equal to 1. Give those a core number of 1, then remove them from the graph.
Repeat above two steps until no such nodes with degree less than or equal to 1 can be found.
Now continue on to nodes of degree less than or equal to 2, etc.

In any case, once you get the details worked out, this would be a great contribution to the algorithms library. Consider submitting a pull request.
