### ISSUE TITLE
Bipartite returns false on clearly bipartite graph?

### ISSUE THREAD

**Issue by prismofeverything** [Engelberg/ubergraph#35]
I have the following digraph:

    (def I-think-this-is-bipartite
     (uber/digraph
      [:datum-a :process-x]
      [:datum-b :process-x]
      [:process-x :datum-c]
      [:datum-c :process-y]
      [:datum-a :process-y]
      [:process-y :datum-d]
      [:process-y :datum-e]
      [:datum-a :process-z]
      [:datum-e :process-z]
      [:process-z :datum-f]))

which I believe is bipartite (am I wrong about this?). However, 

    (alg/bipartite? I-think-this-is-bipartite) --> false

Is my understanding of what a bipartite graph is flawed in some way? Does `bipartite?` not work for digraphs? Some other implementation detail?

Any thoughts or insight welcome, thanks!

**Comment by Engelberg** [comment]
To save me some time analyzing it, can you give me the bipartite breakdown of your example?

**Comment by Engelberg** [comment]
Oh, I see, datums on one side and processes on the other.

**Comment by Engelberg** [comment]
The `bipartite?` comes from loom.  Prior to including it in ubergraph, I eyeballed the loom source to see if it was using anything funky other than the underlying graph protocols, and wasn't making any assumptions that would break in the presence of multigraphs.  In this case, the loom algorithm only relies on the protocols for `nodes` and `successors`, so should be compatible with ubergraph. That's why I included it.

So, it *should* work. I'd have to step through your example with the loom algorithm to try to understand where it is going wrong.  Is it a flaw with the loom algorithm, or something subtle with the way ubergraph implements the protocols?  I probably won't have time to do it this weekend, but could do so early in the week. If you want to expedite the process yourself, I'd encourage you to take the algorithm for `bipartite-color` from loom, copy it into your file, updating the namespace reference for `nodes` and `successors` so you can run it within your file, and then sprinkle in some print statements to see what's going on.  If you find the flaw, please report back.

For reference, here's the loom algorithm for bipartite-color:
https://github.com/aysylu/loom/blob/master/src/loom/alg.cljc#L426

bipartite? just converts the output of that function into a boolean.

**Comment by prismofeverything** [comment]
Hey @Engelberg, thanks for the help! That sounds good, I'll take a look through that function and see what's missing.

**Comment by prismofeverything** [comment]
I will say, https://github.com/aysylu/loom/blob/master/src/loom/alg.cljc#L439 looks suspicious right off the bat.

**Comment by prismofeverything** [comment]
Okay, looks like `successors` only looks at outgoing edges for digraphs, which means if `bipartite-color` starts with a node with incoming but no outgoing edges it receives a color which has no relationship to the color of nodes which are eventually found that do have outgoing edges into it. 

If I change the line https://github.com/aysylu/loom/blob/master/src/loom/alg.cljc#L438 to:

    nbrs (set/union
          (set (graph/predecessors g v))
          (set (graph/successors g v)))]

the function works as expected. 

It would be nice to have a `neighbors` function that consistently returned all neighbors of a node whether it is a graph or a digraph, which I guess is just:

    (defn neighbors
      [graph node]
      (set/union
       (set (uber/predecessors graph node))
       (set (uber/successors graph node))))

**Comment by Engelberg** [comment]
Ah, that makes sense.  Come to think of it, I don't think I've ever seen anyone talk about the term bipartite in the context of directed graphs, only undirected.  Although it is not obvious from looking at loom's code that it makes an assumption of undirectedness.

I'm glad you now have a solution for your purpose.  Not sure what the best solution would be for a general audience.

**Comment by Engelberg** [comment]
I notice now, based on this conversation, that ubergraph's predecessors function is missing a call to `distinct`.  I'll add that and push a new version within a few days.

**Comment by prismofeverything** [comment]
I just opened a PR with the fix over there, we'll see if it works out. Thanks again for the help!

**Comment by prismofeverything** [comment]
> Come to think of it, I don't think I've ever seen anyone talk about the term bipartite in the context of directed graphs, only undirected.

I can't think of a reason the concept of bipartite-ness would be ill-defined for directed graphs, but I am not a graph theorist ; ) In the meantime this does what I need.

**Comment by Engelberg** [comment]
Added call to `distinct` in `predecessors` and pushed as 0.5.3.
