### ISSUE TITLE
Odd behavior for `(add-attr g e k v)` when `e` is edge object from different graph

### ISSUE THREAD

**Issue by jafingerhut** [Engelberg/ubergraph#48]
This is admittedly a bit of a weird corner case, but I was poking through how `add-attr` and other attribute functions work, and found that if you call `(add-attr g e k v)` where `e` is an edge object obtained from a different graph, other than `g`, then the returned graph from `add-attr` is = to the original and pprint looks the same, but it does have an extra key in the :attrs map equal to the :id of the edge `e`.

Here is a sample sequence of things you can eval in the REPL to reproduce the behavior:
```
user=> (def g (uber/graph))
#'user/g
user=> (def g2 (uber/graph [1 2 27]))
#'user/g2
user=> (def e1 (uber/find-edge g2 1 2))
#'user/e1
user=> e1
#ubergraph.core.UndirectedEdge{:id #uuid "2bd264f4-e93d-4e9c-992e-ffaf59b8c5dc", :src 1, :dest 2, :mirror? false}
user=> (def gnew (uber/add-attr g e1 :bar 17))
#'user/gnew
user=> (uber/pprint gnew)
Graph
0 Nodes:
0 Edges:
nil
user=> (= g gnew)
true
user=> (pprint gnew)
{:node-map {},
 :allow-parallel? false,
 :undirected? true,
 :attrs {#uuid "2bd264f4-e93d-4e9c-992e-ffaf59b8c5dc" {:bar 17}},
 :cached-hash #<Atom@7502291e: -1>}
nil
user=> (:attrs g)
{}
user=> (:attrs gnew)
{#uuid "2bd264f4-e93d-4e9c-992e-ffaf59b8c5dc" {:bar 17}}
```

If that is considered a bug, one way to fix it would be changing the function `resolve-node-or-edge`.  Right now `(resolve-node-or-edge g e1)` returns `(:id e1)` if `e1` is an edge object, even if `e1` is not an edge object of the graph `g`.  If instead `(resolve-node-or-edge g e1)` detected that `e1` was not an edge of `g` and returned nil, that might fix the behavior of not only `add-attr`, but also several other attribute functions that have similar behavior as `add-attr` does because of `resolve-node-or-edge`'s behavior in this case.

**Comment by jafingerhut** [comment]
And if `resolve-node-or-edge` was to be changed as described above, I'm sure we would want it to run in as near to constant time as possible, without having to do a linear-time scan through potentially many parallel edges between the nodes of `e1`.

If all edge objects could be assumed to have metadata containing the graph object they came from, we could use that to quickly determine that the edge object did not come from this graph.

**Comment by Engelberg** [comment]
My initial impression is that I don't consider this a bug. If you add an attribute to an edge in a graph where it doesn't exist, I think it's reasonable that it doesn't do anything meaningful, in a garbage-in-garbage-out sense. I'd rather it not break things if you do it, but it doesn't really break things. You end up with an extra bit of info in the attribute map, but it's a meaningless bit of info that doesn't have any impact on the graph, as far as I can tell.  And it seems like an unlikely scenario.

That said, I can see the value of giving a more meaningful error if it doesn't significantly impact performance. And I think this probably _is_ fixable in constant time, because the edges between a given src and dest are a set, and one should be able to just look up the specific Edge object in that set.

I don't think using the metadata graph object is the right way to do it, because if you retrieve the Edge from a graph (let's call it g1) and then proceed to add edges to the graph (let's call it g2), the Edge should be valid in g2 but an identical? test between the graph in Edge's metadata (g1) won't work against g2. The only

**Comment by jafingerhut** [comment]
Yes, I also realized the same problem with trying to use the graph object in edge metadata several hours after suggesting it.

I will think more about the idea of looking up the specific Edge object in the proper set in constant time (or as close as set lookup operations get, which is good enough).  If that does work, it does sound attractive to have an exception thrown for what appears to be an incorrect call.

**Comment by Engelberg** [comment]
Closing the issue for now, but keeping the associated pull request open to potentially reconsider at a future time.
