### ISSUE TITLE
Clojurescript pathfinding

### ISSUE THREAD

**Issue by judepayne** [Engelberg/ubergraph#52]
I currently use Loom in a project in both the clojure and clojurescript environments, but would like to switch to Ubergraph for the multiple edge support - driven by a request by one of my users. I read your advice in a May 2016 issue about clojurescript; to convert the files to .cljc and then remove the parts of 'alg' that rely on Java data structures.
The two Loom algorithms that I need in particular are pre-edge-traversal which looks straightforward to take this approach for and pathfinding which does not since the 'shortest-path' functions does rely on Java data structures.
Do you have any advice or future plans which could help? thanks!

**Comment by Engelberg** [comment]
That advice should still be valid. I recently converted ubergraph to use specter, which runs on clojurescript, but might require some slightly different ns declarations; you'd need to look that up on specter's github page.

As for shortest-path, the basic approach would be to switch the use of Java's Stack over to Clojure's vectors, Java's Queue over to Clojure's PersistentQueue, and Java's PriorityQueue over to the Clojurescript port of priority-map.

Another possibility that might be even easier would be to take a look at Loom's various searching algorithms (which already use Clojure(script) data structures as described above) and see if you can take the one that is relevant to your needs and tweak it to use `out-edges` and `dest` protocol functions so that it correctly handles multiple edges.

**Comment by judepayne** [comment]
Thanks very much. I will take a detailed look at these suggestions

**Comment by johannesloetzsch** [comment]
@judepayne Have you been able to make progress?

Is help on porting to Clojurescript appreciated? I would offer to join in the effort.

**Comment by judepayne** [comment]
Hi @johannesloetzsch no I did not progress this at the time, but I could have some time now to take a proper look (pandemic time!). Before I do, wondering if you were able to progress?

**Comment by judepayne** [comment]
I have had a look at the possibility of converting this library to .cljc as per @Engelberg 's suggestion. Introducing different collections for :cljs in the alg namespace looks doable, but there's more work to do in the core namespace since potemkin is used which is not clojurescript compatible. There's a clojurescript version [here](https://github.com/ztellman/potemkin/issues/31) of import-vars (not tested), but I cannot find an equivalent for def-map-type so Ubergraph would have to fully implement all the core Clojurescript map-related protocols. Continuing to look at this.
