### ISSUE TITLE
Inits vs Manual Graph Creation Differences and find-nodes?

### ISSUE THREAD

**Issue by Folcon** [Engelberg/ubergraph#62]
Hey, thanks for this project, just two questions:
1. Any particular reason that there's no `find-nodes` to go with `find-edges`?
    I wrote an implementation which I'd be happy to PR if you'd like?
```clojure
(defn find-nodes
  "Returns all nodes that match the query"
  [g attrs]
  (reduce
    (fn [v node-id]
      (let [node (select-any (keypath :attrs node-id) g)]
        (if (submap? attrs node)
          (conj v node)
          v)))
    []
    (nodes g)))
```
2. I'm not sure why, but these are different:
```clojure
  (let [g [[:source {:id :source :color "green" :label [:P {:BORDER 1} "SOURCE"]}]
           [:sink {:id :sink :color "red" :label [:P {:BORDER 1} "SINK"]}]
           [:source :sink]]]
    (uber/ubergraph true false g))

  (let [g [^:node [:source {:id :source :color "green" :label [:P {:BORDER 1} "SOURCE"]}]
           ^:node [:sink {:id :sink :color "red" :label [:P {:BORDER 1} "SINK"]}]
           ^:edge [:source :sink]]]
    (uber/ubergraph true false g))
```

These two produce the same data structures, which I've truncated because they're just big:
```clojure
{:node-map {[:source {:id :source, :color "green", :label [:P {:BORDER 1} "SOURCE"]}] #ubergraph.core.NodeInfo{:out-edges {[:sink
                                                                                                                            {:id :sink,
                                                                                                                             :color "red",
                                                                                                                             :label [:P
                                                                                                                                     {:BORDER 1}
                                                                                                                                     "SINK"]}] #{#ubergraph.core.Edge{:id #uuid"d6d7fdb7-8974-466f-b39b-e5cd68b0f6f1",
                                                                                                                                                                      :src [:source
                                                                                                                                                                            {:id :source,
                                                                                                                                                                             :color "green",
                                                                                                                                                                             :label [:P
                                                                                                                                                                                     {:BORDER 1}
                                                                                                                                                                                     "SOURCE"]}],
                                                                                                                                                                      :dest [:sink ...



```
To be honest I was expecting marking what the `^:node` and `^:edge` was would fix it. I even tried putting the `^:node` inside the vector on the first keyword of the node vector.

```clojure
  (let [nodes [[:source {:id :source :color "green" :label [:P {:BORDER 1} "SOURCE"]}]
               [:sink {:id :sink :color "red" :label [:P {:BORDER 1} "SINK"]}]]
        edges [[:source :sink]]]
    (-> (uber/ubergraph true false)
      (as-> $
        (reduce
          (fn [graph [id node]]
            (#'uber/add-node-with-attrs graph [id node]))
          $
          nodes)
        (reduce
          (fn [graph [to from attrs]]
            (#'uber/add-directed-edge graph to from attrs))
          $
          edges))))
```
This last one seems to produce what appears to be the "correct" format?
```clojure
{:node-map {:source #ubergraph.core.NodeInfo{:out-edges {:sink #{#ubergraph.core.Edge{:id #uuid"98f897e6-3bc9-42a9-ac8b-099be226caa9",
                                                                                      :src :source,
                                                                                      :dest :sink}}},
                                             :in-edges {},
                                             :out-degree 1,
                                             :in-degree 0},
            :sink #ubergraph.core.NodeInfo{:out-edges {},
                                           :in-edges {:source #{#ubergraph.core.Edge{:id #uuid"98f897e6-3bc9-42a9-ac8b-099be226caa9",
                                                                                     :src :source,
                                                                                     :dest :sink}}},
                                           :out-degree 0,
                                           :in-degree 1}},
 :allow-parallel? true,
 :undirected? false,
 :attrs {:source {:id :source, :color "green", :label [:P {:BORDER 1} "SOURCE"]},
         :sink {:id :sink, :color "red", :label [:P {:BORDER 1} "SINK"]}},
 :cached-hash #object[clojure.lang.Atom 0x2f06e469 {:status :ready, :val -1}]}
```

Not that I'm certain of that, it's just more compact. No idea if the second one is a bug or expected behaviour? I'm mainly asking as `add-node-with-attrs` and `add-directed-edge` are private functions which is why I'm referencing them directly.

**Comment by Engelberg** [comment]
The ubergraph constructors all are multiple arity, taking multiple inits. They are meant to be used like `(uber/graph init1 init2 init3 ...)` not `(uber/graph vector-of-inits)`, which is what you did. You passed a vector of inits to your constructor, causing weird behavior.

So the fix would be:

```
  (let [g [[:source {:id :source :color "green" :label [:P {:BORDER 1} "SOURCE"]}]
           [:sink {:id :sink :color "red" :label [:P {:BORDER 1} "SINK"]}]
           [:source :sink]]]
    (apply uber/ubergraph true false g))
```

Notice how I added `apply` before the constructor call. No metadata annotations are needed here, because the default resolution order matches what you want. It treats `[keyword map]` as a node with an attribute map, and `[keyword keyword]` as an edge, automatically.

You could also use `uber/multidigraph` as a more concise constructor for the example you gave.

The main purpose for `find-edges` is when you have, for example, a red, green, and blue edge coming out of a given node, and you just want to get at the red one. So we tell it the src node, and the attribute. The src node gets us to a small set of edges, and the color attribute singles out the one we want. This is all reasonably efficient. 

Because the input format for `find-edges` is a kind of query, if you don't specify a src or dest node, it will just search through all the edges for any edge with a given attribute, but that's not in any way efficient, and no better than the user doing their own linear search through all the edges.

I didn't add a `find-nodes` because there's really no use case where it is efficient. It always has to do a linear search through all the nodes. So I didn't see how it provides any additional benefit over the user doing something like:
```
(for [n (uber/nodes g) 
        :when (= (uber/attr g n :color) :red)]
    n)
``` 

By the user doing it themselves, they will better understand the run-time complexity, and won't be misled into thinking that ubergraph has some sort of index of the nodes by attribute.

**Comment by Folcon** [comment]
> Notice how I added apply before the constructor call.

Whoops, that was a really simple mistake, sorry about that >_<...

> I didn't add a find-nodes because there's really no use case where it is efficient. It always has to do a linear search through all the nodes.
> By the user doing it themselves, they will better understand the run-time complexity, and won't be misled into thinking that ubergraph has some sort of index of the nodes by attribute.

Ok, good to understand the reasoning. Thanks!
