### ISSUE TITLE
Heuristics function that takes 2 arguments

### ISSUE THREAD

**Issue by RokLenarcic** [Engelberg/ubergraph#65]
When using `shortest-path` function you can provide:
```
  :heuristic-fn - A function that takes a node as an input and returns a
          lower-bound on the distance to a goal node, used to guide the search
          and make it more efficient.
```

Unfortunately this works poorly when goal node is not known, for instance when looking at all paths starting at a node:
```
;; how do I provide manhattan distance as heuristic here??
(alg/shortest-path g {:start-node p :heuristic-fn ????})
```

**Comment by Engelberg** [comment]
The heuristic function is useful for finding the shortest path more quickly. If you are generating all paths, a heuristic function likely isn't useful.

When you say you want to use manhattan distance as a heuristic, from what to what? What are the two points you want to operate on? If you know absolutely nothing about the goal state, I don't see how manhattan distance could be relevant. If you have multiple possible goals, you could do something like the minimum of the manhattan distance between this node and each of the possible goals.

In my own code, I rarely know anything about the goal, but I can still make an estimate on the minimum number of steps to get to one, because I can tell that reaching the goal will require getting past some minimum number of obstacles that are in the way.

**Comment by RokLenarcic** [comment]
In this case I've got multiple goals, so I guess taking the smallest manhattan distance to any of them is the solution.
