### ISSUE TITLE
Expose loom.graph/subgraph function through ubergraph.core

### ISSUE THREAD

**Issue by dgr** [Engelberg/ubergraph#66]
In general, Ubergraph exposes a lot of loom.graph functions in ubergraph.core. It does not expose loom.graph/subgraph, however. I assume this is just an oversight. If you want, I'll submit a PR with the change.

**Comment by Engelberg** [comment]
That would be great. Thanks for raising this suggestion and offering to submit a PR. Much appreciated.

**Comment by dgr** [comment]
OK, will do. I might find other Loom functions that are similarly unexposed in Ubergraph. To help guide me, what's the philosophy surrounding the relationship between Ubergraph and Loom? Seems like there are two choices:

1. Does Ubergraph want to be a superset of Loom such that a user can just require Ubergraph namespaces and everything in Loom is exposed through those namespaces?
2. Or is Ubergraph an extension to Loom such that some parts of Loom are in Ubergraph, but not all.

It seems like the answer is number 1, but I want to confirm that. If so, it would probably be good to do a completeness check, which I can try to do.

If the answer is number 2, what criteria should be used to determine which functions Ubergraph exposes versus not?

**Comment by Engelberg** [comment]
Ubergraphs implement the loom protocols so that, ideally, loom algorithms
implemented in terms of those protocols will just work on ubergraphs. In
practice, some loom algorithms aren't implemented in terms of protocols,
some loom algorithms don't make sense for graphs that can have multiple
edges between nodes, and some loom algorithms can be implemented more
efficiently leveraging ubergraph's implementation details. So I like to
think of ubergraph's alg namespace as a *curated* set of loom algorithms.
So the philosophy is that a loom algorithm should be exposed through
ubergraph's alg namespace if it is confirmed to work on ubergraphs, or has
been given its own ubergraph-specific implementation.

**Comment by dgr** [comment]
See PR.

**Comment by Engelberg** [comment]
Fixed
